# Site settings
course_name: Machine Learning Practico
course_description: "En este curso tomamos un problema y vamos a intentar solucionarlo utilizando Machine Learning. Intentarlo nos va a obligar a ver algunos temas que considero relevantes para la aplicaci칩n de Machine Learning, desde un punto de vista te칩rico, pr치ctico y metodol칩gico."

course_semester: "2020"

baseurl: "/machine-learning-practico" # the subpath of your site, e.g. /blog/
url: "http://elsonidoq.github.io/" # the base hostname & protocol for your site

schoolname: ""
schoolurl: ""
twitter_username: ideasrapidas 

address: ""

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: false
    lectures:
        output: false
    assignments:
        output: false
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"

theme: jekyll-theme-slate
